# Basic Information 
title: Kaili(Kelly) Zhang
position: Ph.D. Student
affiliation: Texas A&M University
affiliation_link: https://www.tamu.edu/
affiliation_logo: ./assets/img/tamu-coa-logo-20240816.svg
email: kelly_zhang@tamu.edu

# Search Engine Optimization (SEO)
keywords: Kaili Zhang, Kelly Zhang, Zhang Kaili, kailizhang
description: Kaili(Kelly) Zhang is a Ph.D. student at the University of Texas A&M University. Her research lies in urban studies, spatial analysis, machine learning, Ecological Footprint and climate justice.

# The option is used to enable the TAMU template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=Z9rfcV0AAAAJ&hl
github_link: https://github.com/kellyzhang8/
linkedin: https://www.linkedin.com/in/kaili-zhang-966ab42a8/
twitter: https://twitter.com/KellyLee012/

# Images 
avatar: https://i.postimg.cc/7ZCwCLNx/IMG-0487.jpg

# Footnotes
footnote: Feel free to use my website's source code.
footnote_link: https://github.com/kellyzhang8/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
# clustrmaps_id: CJD8XwsJhSyQ6sbsU-Gw0cNcUlbah7KW3xvHN2QlwW0

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
